flag-message: "&3Arctic &r&7/ &b%player% &7flagged &b%check% &7(&3Type %type%&7) (&b%vl%&7/&b%maxvl%&7)"
flag-message-verbose: "&3Arctic &r&7/ &b%player% &7[&e%ping%ms&7] &7flagged &3%check% &7(%type%&7) &fx%vl% &7[TPS=%tps%]"
ban-command: "kick %player% &3Arctic &r&7/ &bDetected for cheating"

bypass-enabled: false
bypass-permission: arctic.bypass

checks:
  movement:
    fly:
      a:
        ban-vl: 10
        enabled: true
        punish: true
      b:
        ban-vl: 10
        enabled: true
        punish: true
      c:
        ban-vl: 10
        enabled: true
        punish: true
    speed:
      a:
        ban-vl: 10
        enabled: true
        punish: true
    step:
      a:
        ban-vl: 10
        enabled: true
        punish: true
    nofall:
      a:
        ban-vl: 10
        enabled: true
        punish: true
      b:
        ban-vl: 10
        enabled: true
        punish: true
    motion:
      a:
        ban-vl: 10
        enabled: true
        punish: true
  combat:
    autoclicker:
      a:
        ban-vl: 50
        enabled: true
        punish: true
      b:
        ban-vl: 50
        enabled: true
        punish: true
      c:
        ban-vl: 50
        enabled: true
        punish: true
    killaura:
      a:
        ban-vl: 10
        enabled: true
        punish: true
      b:
        ban-vl: 10
        enabled: true
        punish: true
      c:
        ban-vl: 10
        enabled: true
        punish: true
      d:
        ban-vl: 10
        enabled: true
        punish: true
      e:
        ban-vl: 10
        enabled: true
        punish: true
      f:
        ban-vl: 10
        enabled: true
        punish: true
      i:
        ban-vl: 50
        enabled: true
        punish: true
    reach:
      a:
        ban-vl: 10
        enabled: true
        punish: true
    aim:
      a:
        ban-vl: 50
        enabled: true
        punish: true
      b:
        ban-vl: 50
        enabled: true
        punish: true
      c:
        ban-vl: 50
        enabled: true
        punish: true
      d:
        ban-vl: 50
        enabled: true
        punish: true
      e:
        ban-vl: 50
        enabled: true
        punish: true
      f:
        ban-vl: 50
        enabled: true
        punish: true
      g:
        ban-vl: 50
        enabled: true
        punish: true
      h:
        ban-vl: 50
        enabled: true
        punish: true
      i:
        ban-vl: 50
        enabled: true
        punish: true
      j:
        ban-vl: 50
        enabled: true
        punish: true
      k:
        ban-vl: 50
        enabled: true
        punish: true
      l:
        ban-vl: 50
        enabled: true
        punish: true
      m:
        ban-vl: 50
        enabled: true
        punish: true
    velocity:
      a:
        ban-vl: 50
        enabled: true
        punish: true
  player:
    badpackets:
      a:
        ban-vl: 20
        enabled: true
        punish: true
      b:
        ban-vl: 5
        enabled: true
        punish: true
      c:
        ban-vl: 5
        enabled: true
        punish: true
    scaffold:
      a:
        ban-vl: 120
        enabled: true
        punish: true
    timer:
      a:
        ban-vl: 500
        enabled: true
        punish: true