flag-message: "&b&lPolar &r&7/ &b%player% &7flagged &b%check% &7(%type%&7) &fx%vl%"
ban-command: "kick %player% &b&lPolar &r&7/ &bDetected for cheating"

checks:
  movement:
    fly:
      a:
        ban-vl: 10
        enabled: true
        punish: true
      b:
        ban-vl: 10
        enabled: true
        punish: true
      c:
        ban-vl: 10
        enabled: true
        punish: true
    speed:
      a:
        ban-vl: 10
        enabled: true
        punish: true
    step:
      a:
        ban-vl: 10
        enabled: true
        punish: true
    nofall:
      a:
        ban-vl: 10
        enabled: true
        punish: true
  combat:
    autoclicker:
      a:
        ban-vl: 50
        enabled: true
        punish: true
      b:
        ban-vl: 50
        enabled: true
        punish: true
    killaura:
      a:
        ban-vl: 10
        enabled: true
        punish: false
      b:
        ban-vl: 10
        enabled: true
        punish: true
      c:
        ban-vl: 10
        enabled: true
        punish: true
      d:
        ban-vl: 10
        enabled: true
        punish: true
      e:
        ban-vl: 10
        enabled: true
        punish: true
    reach:
      a:
        ban-vl: 10
        enabled: true
        punish: true
    entity:
      a:
        ban-vl: 25
        enabled: true
        punish: false
    aim:
      a:
        ban-vl: 50
        enabled: true
        punish: false
      b:
        ban-vl: 50
        enabled: true
        punish: false
      c:
        ban-vl: 50
        enabled: true
        punish: false
      d:
        ban-vl: 50
        enabled: true
        punish: false
      e:
        ban-vl: 50
        enabled: true
        punish: false

