
flag-message: "&c&lHoneyBadger &f| &c%player% &7flagged &c%check% &7(%type%&7) &fx%vl%"
ban-command: "kick %player% &c&lHoneyBadger &f| &cDetected for cheating%"

checks:
  movement:
    fly:
      a:
        ban-vl: 10
        enabled: true
        punish: false
    speed:
      a:
        ban-vl: 10
        enabled: true
        punish: false
