name: Arctic
main: arctic.ac.Arctic
version: 0.0.1
authors: [ Salers,xWand,ExDiggers,Aamber ]
load: POSTWORLD
depend:
  - ProtocolLib
softdepend: [ Citizens ]

commands:
  arctic:
    permission: arctic.admin
  alerts:
    permission: arctic.alerts
  debug:
    permission: arctic.debug
  info:
    permission: arctic.info