name: Polar
main: polar.ac.Polar
version: 0.0.1
authors: [Salers,xWand,ExDiggers]
load: STARTUP
depend:
  - ProtocolLib

commands:
  polar:
    permission: polar.command
  alerts:
    permission: alerts.command
  debug:
    permission: debug.command
  hbreload:
    permission: preload.command
  hbsettings:
    permission: psettings.command
