name: Polar
main: polar.ac.Polar
version: 0.0.1
authors: [Salers,xWand,ExDiggers]
load: STARTUP
depend:
  - ProtocolLib
softdepend: [Citizens]

commands:
  polar:
    permission: polar.command
  alerts:
    permission: alerts.command
  debug:
    permission: debug.command
  preload:
    permission: preload.command
  psettings:
    permission: psettings.command
