name: Arctic
main: arctic.ac.Arctic
version: 0.0.1
authors: [ Salers,xWand,ExDiggers,Aamber ]
load: STARTUP
depend:
  - ProtocolLib
softdepend: [ Citizens ]

commands:
  arctic:
    permission: arctic.command
  alerts:
    permission: alerts.command
  debug:
    permission: debug.command
  areload:
    permission: areload.command
  asettings:
    permission: asettings.command
