name: Arctic
main: dev.arctic.anticheat.ArcticPlugin
authors: [ SalersFR,Crafticat, xWand, DerRedstoner ]
version: 0.1
description: A minecraft anticheat

commands:
  arctic:
    permission: arctic.admin
  alerts:
    permission: arctic.alerts
  debug:
    permission: arctic.debug
  info:
    permission: arctic.info